server:
 port: 8082

spring:
  datasource:
  url: jdbc:oracle:thin:@localhost:1521:xe
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
    show-sql: false
  driver-class: oracle.jdbc.driver.OracleDriver